services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb

    volumes:
      - ./.postgres:/var/lib/postgresql/data

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
